# Generated by Django 5.0.4 on 2024-05-28 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0002_alter_customuser_is_active_alter_customuser_is_admin_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
