# Generated by Django 5.0.4 on 2024-05-29 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_first_name_customuser_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
